[package]
name = "portal"
version = "0.1.0"
authors = ["landhb <landhb@github>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
portal-lib = { path = "../lib" }
mio = {version = "0.7", features = ["os-poll", "tcp"]}
anyhow = "1.0.32"
clap = "2.33.3"
